format_version: 10
pipelines:
  expense-tf-destroy:
    group: TerraformGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-649cad1:
        git: https://github.com/s-devops-i1/expense-terraform.git
        shallow_clone: false
        auto_update: true
        branch: main
    secure_variables:
      TF_VAR_vault_token: AES:NJL2N1fIqEU8JUAOUDqu9A==:Qx4gcAcAcpxwUPBHQyQNqUWkoOzmGtxxpOpw76G2XfQ=
    stages:
      - DEV:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: manual
            allow_only_on_success: false
          jobs:
            terraform-destroy:
              timeout: 0
              tasks:
                - exec: {command: terraform, arguments: [ "init", "-backend-config=env-dev/state.tfvars"], run_if: passed }
                - exec: {command: terraform, arguments: [ "destroy", "-var-file=env-dev/main.tfvars", "-auto-approve" ], run_if: passed }


